Added bad ANSIBLE_LOCAL_HOME location

diff --git a/ansible-docker-run b/ansible-docker-run
--- a/ansible-docker-run
+++ b/ansible-docker-run
@@ -2,6 +2,32 @@
 # Run the Ansible docker image
 # This script is called from the other one
 
+# flag
+# e - Exit if any error
+# u - Treat unset variables as an error when substituting
+# o pipefail - the return value of a pipeline is the status of the last command to exit with a non-zero status or zero if no command exited with a non-zero status
+# E - the ERR trap is inherited by shell functions
+set -Eeuo pipefail
+
+CLI_NAME=$(basename "$0") # Name of the cli
+
+## A trap on ERR, if set, is executed before the shell exits.
+# Because we show the $LINENO, we can;t create a function otherwise the line number would be not correct
+trap 'echo_err ""; echo_err "Command error on line ($0:$LINENO)"; exit 1' ERR
+
+# Echo a message
+function echo_log() {
+  echo -e "$CLI_NAME: ${1:-}"
+}
+# Print the error message $1
+function echo_err() {
+  RED='\033[0;31m'
+  NC='\033[0m' # No Color
+  #(>&2 echo -e "${RED}$1${NC}")
+  echo_log "${RED}$1${NC}"
+}
+
+
 if [[ $(uname -a) =~ "CYGWIN" ]]; then
   CYGWIN=1
 else
@@ -36,7 +62,12 @@ DOCKER_WORKING_DIR="/ansible/playbooks"
 
 # Mounting the current directory or the home if set
 PWD_DOCKER_FORMAT=$(pwd)
-if [ -n "$ANSIBLE_LOCAL_HOME" ]; then
+ANSIBLE_LOCAL_HOME=${ANSIBLE_LOCAL_HOME:-}
+if [ "$ANSIBLE_LOCAL_HOME" != "" ]; then
+  if [ ! -d "$ANSIBLE_LOCAL_HOME" ]; then
+      echo_err "The local ansible home directory ($ANSIBLE_LOCAL_HOME) of the ANSIBLE_LOCAL_HOME variable does not exist. Are you sure that your ansible project is located there?"
+      exit 1;
+  fi
   PWD_DOCKER_FORMAT=$ANSIBLE_LOCAL_HOME;
 fi;
 if [ $CYGWIN = 1 ] ; then
@@ -91,26 +122,33 @@ echo "ANSIBLE_HOME   : $DOCKER_WORKING_DIR/$ANSIBLE_HOME"
 echo
 
 # Azure
-if [ -n "$AZURE_CLIENT_ID" ]; then
+AZURE_CLIENT_ID=${AZURE_CLIENT_ID:-}
+if [ "$AZURE_CLIENT_ID" != "" ]; then
     args+=("--env" "AZURE_CLIENT_ID=$AZURE_CLIENT_ID")
 fi
-if [ -n "$AZURE_SECRET" ]; then
+AZURE_SECRET=${AZURE_SECRET:-}
+if [ "$AZURE_SECRET" != "" ]; then
     args+=("--env" "AZURE_SECRET=$AZURE_SECRET")
 fi
+AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID:-}
 if [ -n "$AZURE_SUBSCRIPTION_ID" ]; then
     args+=("--env" "AZURE_SUBSCRIPTION_ID=$AZURE_SUBSCRIPTION_ID")
 fi
-if [ -n "$AZURE_TENANT" ]; then
+AZURE_TENANT=${AZURE_TENANT:-}
+if [ "$AZURE_TENANT" != "" ]; then
     args+=("--env" "AZURE_TENANT=$AZURE_TENANT")
 fi
 
 # Hcloud
 # https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/docsite/guides.html
-if [ -n "$HCLOUD_TOKEN" ]; then
+HCLOUD_TOKEN=${HCLOUD_TOKEN:-}
+if [ "$HCLOUD_TOKEN" != "" ]; then
     args+=("--env" "HCLOUD_TOKEN=$HCLOUD_TOKEN")
 fi
 
+
 # Run Docker command
+
 docker "${args[@]}" \
 	gerardnico/ansible:"$ANSIBLE_VERSION" \
 	"$@"
